# Generated by Django 5.2.4 on 2025-07-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.patient')),
            ],
        ),
    ]
